### ISSUE TITLE
CSS minification breaks CSS

### ISSUE THREAD

**Issue by trusktr** [neoascetic/rawgithack#59]
Example code:

```css
/* Checkboxes and radios share much of the same code. */
@import './input.shared.css';

input[type='checkbox' i] {
	/* Checkboxes are boxes with rounded corners. */
	--checkable-border-radius: 15%;
}

input[type='checkbox' i]:before {
	border-top: none;
	border-left: none;
	border-radius: 0;
	background: none;
	height: calc(var(--checkable-mark-scale) * 55%);
	width: calc(var(--checkable-mark-scale) * 28%);
}
```

Output example:

```css
@import './input.shared.css';input[type=checkboxi]{--checkable-border-radius: 15%}input[type=checkboxi]:before{border-top:none;border-left:none;border-radius:0;background:0 0;height:calc(var(--checkable-mark-scale) * 55%);width:calc(var(--checkable-mark-scale) * 28%)}
```

URL: https://rawcdn.githack.com/lume/basicss/1a2352cf30c07494ede015bb13b6e81bd26c4f9a/src/elements/input/input-checkbox.css

Notice the `i` values inside the attribute selectors have been squashed onto the attribute values. The CSS no longer works when this happens.
