### ISSUE TITLE
Minification not working?

### ISSUE THREAD

**Issue by Phroneris** [neoascetic/rawgithack#74]
### URL

https://rawcdn.githack.com/neoascetic/rawgithack/825fd5c5403ef4a9796cbfb6835511773215e615/web/rawgithack.css?min=1

### Expected Result

```css
html{background:#fff;color:#333}...
```

### Actual Result

```css
html {
  background: #fff;
  color: #333;
}
...
```

Hmm, what's happening?

The url is in-production one and has trailing `?min=1`.
The revision specifier (`825fd5c...`) is using a commit hash rather than a branch name.
But the result isn't minified.

Am I missing anything else?

Environment: Windows 10, Google Chrome
